development:
  adapter: mysql2
  database: wc_development
  username: wc_admn
  password: pass13!#
  encoding: utf8
  pool: 5
 
test: 
  adapter: mysql2
  database: wc_test
  username: rails
  password: rails.pass13!#
  encoding: utf8
  pool: 5
